### PR TITLE
add mingw binaries, small fix in Makefile

### PR DESCRIPTION
**Pull request by vwaurich**

### CODE REVIEW

**Comment by tbeu** [comment]
Did you get a successful build libhdf5.a as well?

**Comment by vwaurich** [comment]
No. Only the targets in the Makefile.

**Comment by tbeu** [comment]
Does it still work in OMC if the standard conform library directories of Modelica 3.4 are utilized, i.e. Library\mingw32 -> Library\win32\mingw or Library\win32\mingw48 ?

**Comment by vwaurich** [comment]
No. omc searches in \mingw32 and \win32 only.  \win32\mingw is not a search path.

**Comment by tbeu** [comment]
About libhdf5.a: I believe OMC installs a proper libhdf5.a such that the linking works. If yes, we could also remove libzlib.a which aloso comes along with OMC. Can you please update your PR and remove libzlib.a again.
Which gcc version did you use?

**Comment by tbeu** [comment]
Having the mingw binaries also in Library\win32 would make MinGW compiler work in Dymola. Is it possible to have links between files in a git repo?

**Comment by vwaurich** [comment]
Shouldn't we leave the libzlib.a ?Maybe there is some tool out there which does not link libzlib by default.
I used gcc 5.3.0

**Comment by tbeu** [comment]
> Maybe there is some tool out there which does not link libzlib by default.

There is no other tool searching ming32 and ming64 directories for library dependencies.

I will update the PR with binaries built with gcc48. I need to be able to build the MinGW binaries anyway.

**Comment by tbeu** [comment]
I am going to add the MinGW binaries in an extra release package (as it is generally not good practice to have all those bianries in a repository).

**Pull request closed without merging**
