### PR TITLE
JSON Arrays

### PR DESCRIPTION
**Pull request by harmanpa**
This pull-request adds the ability to read 1D and 2D arrays of Real / Integer / Boolean / String types from JSON files. Functions are added to ExternData.JSONFile to read each of these.

The JSON implementation has been changed to use Parson (https://github.com/kgabis/parson) instead of bsxml-json, as bsxml-json does not support numerical / boolean values or strings containing special characters and it's API for arrays is insufficient.

It is built for Windows 32 and 64 with Visual Studio 2010 and tested with Dymola 2018.

### CODE REVIEW

**Comment by dietmarw** [comment]
I would accept this until I see a test on Linux :stuck_out_tongue:

**Comment by harmanpa** [comment]
Very kind of you to volunteer to test it @dietmarw :-)

**Comment by hyumo** [comment]
It would be great if we can have dynamic 2d arrays for `csv`, `xml`, `xls` and `xlsx` too for consistency.

**Comment by tbeu** [comment]
Thank you. Merged manually. Updated binaries will follow soon.

**Pull request closed without merging**
