### PR TITLE
Updates the build status link to use the travis-ci service. 

### PR DESCRIPTION
**Pull request by dietmarw**
Best to accept this PR **after** you've activated ExternData under https://travis-ci.org/tbeu/ExternData/

### CODE REVIEW

**Comment by tbeu** [comment]
Ah.

**Comment by tbeu** [comment]
On drone.io I chose GCC 4.8 whereas travis has GCC 4.6. Any idea how to force 4.8 on travis?

**Comment by tbeu** [comment]
Merged.

**Comment by dietmarw** [comment]
Yes i can fix that tomorrow. You could evev configure a build matrix with all kind of compilers

**Pull request closed without merging**
